import type { NextPage } from "next";
import Head from "next/head";
import { Navbar, Button } from "@mayurarx/ooredoo-design-system";
import { useState } from "react";

const Home: NextPage = () => {
  let [activeLink, setActiveLink] = useState("");

  return (
    <>
      <Head>
        <title>Ooredoo | Dashboard | Demo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar
        activeHref={activeLink}
        onSearch={(key) => {
          setActiveLink(key);
        }}
        className="fixed left-1/2 w-full -translate-x-1/2"
      />

      <div className="mx-auto flex h-screen max-w-[1280px] flex-col items-center justify-center space-y-4">
        <p className="text-2xl">Welcome to Ooredoo Dashboard</p>
        <Button variant="filled" className="rounded-md px-6 py-3">
          Get Started
        </Button>
      </div>
    </>
  );
};

export default Home;
